### ISSUE TITLE
hi你好，我没有生成patch_signed_7zip

### ISSUE THREAD

**Issue by zktzktzkt** [lihangleo2/TinkerDemo#2]
tinkerPatchDebug 我按照步骤一步一步的做了，可是只出现了 app-debug、old-app、tinker_result这三个文件夹，没有出现任何apk文件

**Comment by lihangleo2** [comment]
你好，你直接用我的demo跑。跟着我的步骤去走。跑通了以后再集成到你的醒目里。 我demo就如我的博客里那样，是我亲测过的

zktzktzkt <notifications@github.com> 于2019年12月11日周三 上午11:58写道：
